// <auto-generated />
using MMCourseStore.Modules.Students.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MMCourseStore.Modules.Students.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("student")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MMCourseStore.Modules.Students.Domain.Student", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Students", "student");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Hassan",
                            LastName = "Rezaei"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Mohammad",
                            LastName = "Hassani"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Aria",
                            LastName = "Zohoori"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Reza",
                            LastName = "Abbasi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
